version: "3.2"

services:
  app:
    image: anoop/spring-rest-service
    depends_on: 
      - postgres
    ports:
      - 8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: Password1234
